version: '3.9'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: pim_php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html

  nginx:
    image: nginx:1.25
    container_name: pim_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: pim_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pim
      MYSQL_USER: pim
      MYSQL_PASSWORD: pim
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pim_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

